#!/bin/bash

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)" # 获取工作目录
MNC_DIR="${BASE_DIR}/run/mnc_exp_*" # MNC文件目录
OUT_DIR="${BASE_DIR}/output" # 输出目录
FIXED_OUT=("state" "phiHyd" "phiHydLow") # 模式固定输出
DIAG_OUT=("surf" "dync") # 诊断输出
STATIS_OUT=("stat")
mkdir -p "$OUT_DIR"

gluemncbig -o "$OUT_DIR/grid.nc" $MNC_DIR/grid.t*.nc
for var in "${FIXED_OUT[@]}"; do
    gluemncbig -o "$OUT_DIR/${var}.nc" $MNC_DIR/${var}.*.t*.nc
done

# 处理诊断输出（如果存在）
for var in "${DIAG_OUT[@]}"; do
    files=$(ls $MNC_DIR/${var}.*.t*.nc 2>/dev/null)
    if [ -n "$files" ]; then
        gluemncbig -o "$OUT_DIR/${var}.nc" $files
    else
        echo "输出 $var 不存在，跳过。"
    fi
done

for var in "${STATIS_OUT[@]}"; do
    latest_file=$(ls -v $MNC_DIR/${var}.*.t001.nc 2>/dev/null | sort -r | head -n 1)
    if [ -n "$latest_file" ]; then
        cp  "$latest_file" "$OUT_DIR"
    else
        echo "未找到匹配文件：$MNC_DIR/${var}.*.t001.nc"
    fi
done